/* Populate database with sample data. */

INSERT INTO animals (NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG ) VALUES ('Agumon' , '2020-02-03', 0 , true, 10.23);
INSERT INTO animals (NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG ) VALUES ('Gabumon' , '2018-11-15', 2 , true, 8);
INSERT INTO animals (NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG ) VALUES ('Pikachu' , '2021-01-07', 1 , false, 15.04);
INSERT INTO animals (NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG ) VALUES ('Devimon' , '2017-05-12', 5 , true, 11);

INSERT INTO animals (NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG ) VALUES ('Charmander' , '2020-02-08', 0 , false, -11);
INSERT INTO animals (NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG ) VALUES ('Plantmon' , '2021-11-15', 2 , ture, -5.7);
INSERT INTO animals (NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG ) VALUES ('Squirtle' , '1993-04-02', 3 , false, -12.13);
INSERT INTO animals (NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG ) VALUES ('Angemon' , '2005-06-12', 1 , true, -45);
INSERT INTO animals (NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG ) VALUES ('Boarmon' , '2005-06-07', 7 , true, 20.4);
INSERT INTO animals (NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG ) VALUES ('Blossom' , '1998-09-13', 3 , true, 17);
INSERT INTO animals (NAME,DATE_OF_BIRTH,ESCAPE_ATTEMPTS,NEUTERED,WEIGHT_KG ) VALUES ('Ditto' , '2022-05-14', 4 , true, 22);

-- Insert Owners

INSERT INTO OWNERS (FULL_NAME, AGE) VALUES ('Sam Smith' , 34); 
INSERT INTO OWNERS (FULL_NAME, AGE) VALUES ('Jennifer Orwell' , 19); 
INSERT INTO OWNERS (FULL_NAME, AGE) VALUES ('Bob' , 45); 
INSERT INTO OWNERS (FULL_NAME, AGE) VALUES ('Melody Pond ' , 77); 
INSERT INTO OWNERS (FULL_NAME, AGE) VALUES ('Dean Winchester' , 14); 
INSERT INTO OWNERS (FULL_NAME, AGE) VALUES ('Jodie Whittaker' , 38); 

/*
** INSERT SPECIES 
*/

INSERT INTO SPECIES (NAME) VALUES ('Pokemon'); 
INSERT INTO SPECIES (NAME) VALUES ('Digimon'); 

/*
** Modify Animals 
*/

-- species_id
UPDATE ANIMALS SET SPECIES_ID = (SELECT ID FROM SPECIES WHERE NAME = 'Digimon') WHERE NAME LIKE '%mon';
UPDATE ANIMALS SET SPECIES_ID = (SELECT ID FROM SPECIES WHERE NAME = 'Pokemon') WHERE NAME NOT LIKE '%mon';

-- owner_id

UPDATE ANIMALS SET OWNER_ID = (SELECT ID FROM OWNERS WHERE full_name  = 'Sam Smith') WHERE NAME IN('Agumon'); 
UPDATE ANIMALS SET OWNER_ID = (SELECT ID FROM OWNERS WHERE full_name  = 'Jennifer Orwell') WHERE NAME IN('Gabumon' , 'Pikachu'); 
UPDATE ANIMALS SET OWNER_ID = (SELECT ID FROM OWNERS WHERE full_name  = 'Bob') WHERE NAME IN('Devimon', 'Plantmon'); 
UPDATE ANIMALS SET OWNER_ID = (SELECT ID FROM OWNERS WHERE full_name  = 'Melody Pond ') WHERE NAME IN('Charmander', 'Squirtle', 'Blossom'); 
UPDATE ANIMALS SET OWNER_ID = (SELECT ID FROM OWNERS WHERE full_name  = 'Dean Winchester') WHERE NAME IN('Angemon' , 'Boarmon'); 


-- Vets data

INSERT INTO VETS (NAME, AGE, DATE_OF_GRADUATION) VALUES ('William Tatche' , 45 , '2020-04-23');
INSERT INTO VETS (NAME, AGE, DATE_OF_GRADUATION) VALUES ('Maisy Smith' , 26 , '2019-01-17');
INSERT INTO VETS (NAME, AGE, DATE_OF_GRADUATION) VALUES ('Stephanie Mendez' , 64 , '1981-05-04');
INSERT INTO VETS (NAME, AGE, DATE_OF_GRADUATION) VALUES ('Jack Harkness' , 38 , '2008-06-08');

-- Specialties data 

INSERT INTO specializations (SPECIES_ID, VETS_ID) SELECT SPECIES.ID, VETS.ID FROM SPECIES INNER JOIN VETS ON SPECIES.NAME = 'Pokemon' AND VETS.NAME = 'William Tatche';
INSERT INTO specializations (SPECIES_ID, VETS_ID) SELECT SPECIES.ID, VETS.ID FROM SPECIES INNER JOIN VETS ON SPECIES.NAME In('Pokemon', 'Digimon') AND VETS.NAME = 'Stephanie Mendez';
INSERT INTO specializations (SPECIES_ID, VETS_ID) SELECT SPECIES.ID, VETS.ID FROM SPECIES INNER JOIN VETS ON SPECIES.NAME = 'Digimon' AND VETS.NAME = 'Jack Harkness';

