CREATE TABLE INVOICES (
    ID INT GENERATED ALWAYS AS IDENTITY, 
    TOTAL_AMOUNT DECIMAL NOT NULL,
    GENERATED_AT DATE NOT NULL,
    PAYED_AT DATE NOT NULL,
    MEDICAL_HISTORY_ID INT, 

    PRIMARY KEY (ID);
);

CREATE TABLE INVOICE_ITEMS(
    ID INT GENERATED ALWAYS AS IDENTITY, 
    UNIT_PRICE DECIMAL NOT NULL, 
    QUANTITY INT NOT NULL,
    TOTAL_PRICE DECIMAL NOT NULL,
    INVOICE_ID INT NOT NULL,
    TREATMENT_ID INT NOT NULL,

    PRIMARY KEY (ID);
);

