/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    ID INT GENERATED ALWAYS AS IDENTITY, 
    NAME VARCHAR(255) NOT NULL, 
    DATE_OF_BIRTH DATE NOT NULL,
    ESCAPE_ATTEMPTS INT NOT NULL, 
    NEUTERED BOOLEAN NOT NULL, 
    WEIGHT_KG DECIMAL NOT NULL, 
    SPECIES VARCHAR(255) NOT NULL, 
    
    PRIMARY KEY(ID) 
);
