/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    ID INT GENERATED ALWAYS AS IDENTITY, 
    NAME VARCHAR(255) NOT NULL, 
    DATE_OF_BIRTH DATE NOT NULL,
    ESCAPE_ATTEMPTS INT NOT NULL, 
    NEUTERED BOOLEAN NOT NULL, 
    WEIGHT_KG DECIMAL NOT NULL, 

    PRIMARY KEY(ID) 
);

ALTER TABLE animals ADD SPECIES VARCHAR(255);

CREATE TABLE owners (
    ID INT GENERATED ALWAYS AS IDENTITY, 
    FULL_NAME VARCHAR(255) NOT NULL, 
    AGE INT NOT NULL,

    PRIMARY KEY (ID)
);

CREATE TABLE species (
    ID INT GENERATED ALWAYS AS IDENTITY, 
    NAME VARCHAR(255) NOT NULL, 

    PRIMARY KEY (ID)
);

ALTER TABLE animals DROP COLUMN SPECIES; 

ALTER TABLE animals ADD COLUMN SPECIES_ID INT; 
ALTER TABLE animals ADD CONSTRAINT SPECIES_FK FOREIGN KEY (SPECIES_ID) REFERENCES species(ID)
ON DELETE CASCADE;

ALTER TABLE animals ADD COLUMN OWNER_ID INT; 
ALTER TABLE animals ADD CONSTRAINT OWNER_FK FOREIGN KEY (OWNER_ID) REFERENCES owners(ID)
ON DELETE CASCADE;