/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    ID INT GENERATED ALWAYS AS IDENTITY, 
    NAME VARCHAR(255) NOT NULL, 
    DATE_OF_BIRTH DATE NOT NULL,
    ESCAPE_ATTEMPTS INT NOT NULL, 
    NEUTERED BOOLEAN NOT NULL, 
    WEIGHT_KG DECIMAL NOT NULL, 

    PRIMARY KEY(ID) 
);

ALTER TABLE animals ADD SPECIES VARCHAR(255);

CREATE TABLE owners (
    ID INT GENERATED ALWAYS AS IDENTITY, 
    FULL_NAME VARCHAR(255) NOT NULL, 
    AGE INT NOT NULL,

    PRIMARY KEY (ID)
);

CREATE TABLE species (
    ID INT GENERATED ALWAYS AS IDENTITY, 
    NAME VARCHAR(255) NOT NULL, 

    PRIMARY KEY (ID)
);

ALTER TABLE animals DROP COLUMN SPECIES; 

ALTER TABLE animals ADD COLUMN SPECIES_ID INT; 
ALTER TABLE animals ADD CONSTRAINT SPECIES_FK FOREIGN KEY (SPECIES_ID) REFERENCES species(ID)
ON DELETE CASCADE;

ALTER TABLE animals ADD COLUMN OWNER_ID INT; 
ALTER TABLE animals ADD CONSTRAINT OWNER_FK FOREIGN KEY (OWNER_ID) REFERENCES owners(ID)
ON DELETE CASCADE;

CREATE TABLE vets(
    ID INT GENERATED ALWAYS AS IDENTITY, 
    NAME VARCHAR(255) NOT NULL, 
    AGE INT NOT NULL, 
    DATE_OF_GRADUATION DATE NOT NULL, 

    PRIMARY KEY (ID)
);

CREATE TABLE specializations(
    ID INT GENERATED ALWAYS AS IDENTITY,
    species_id INT , 
    vets_id INT, 

    CONSTRAINT SPECIES_FOREIGN
    FOREIGN KEY (species_id)
    REFERENCES SPECIES(ID), 

    CONSTRAINT VETS_FOREIGN
    FOREIGN KEY (vets_id)
    REFERENCES VETS(ID)

);

CREATE TABLE VISITS (
    ID INT GENERATED ALWAYS AS IDENTITY, 
    ANIMALS_ID INT, 
    VETS_ID INT, 
    VISIT_DATE DATE, 

    CONSTRAINT ANIMALS_FOREIGN 
    FOREIGN KEY (ANIMALS_ID)
    REFERENCES ANIMALS(ID), 

    CONSTRAINT VETS_FOREIGN 
    FOREIGN KEY (VETS_ID)
    REFERENCES VETS(ID)
); 

ALTER TABLE owners ADD COLUMN email VARCHAR(120);

CREATE INDEX ON VISITS(animals_id);
CREATE INDEX ON VISITS(vets_id);
CREATE INDEX ON owners(email);